[package]
name = "ex002"
version = "0.1.0"
authors = ["Javier Leyba <135663+xleyba@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
